packages:
  - 'test/**'
  - 'playground'

allowBuilds:
  core-js: false
  simple-git-hooks: false

minimumReleaseAgeExclude:
  - '@rsbuild/*'
  - '@rslib/*'
  - '@rslint/*'
  - '@rspack/*'
  - '@rspress/*'
  - '@rstackjs/*'
  - '@rstest/*'
  - 'rsbuild-plugin-*'
  - rstack
